name: StatisticsPlugin
version: '1.0-SNAPSHOT'
main: com.github.saintedlittle.Main
api-version: '1.20'

commands:
  synchronize:
    description: Synchronize player data.
    usage: /synchronize <player>
    permission: statistics.synchronize
    permission-message: "You do not have permission to use this command."

permissions:
  statistics.synchronize:
    description: Allows the use of the /synchronize command.
    default: true

  statistics.synchronize.other:
    description: Allows the /synchronize command to be used on other players.